# Generated by Django 4.2.6 on 2023-11-26 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservaciones',
            fields=[
                ('idreserva', models.AutoField(db_column='IdReserva', primary_key=True, serialize=False)),
                ('fechaentrada', models.DateField(db_column='FechaEntrada')),
                ('fechasalida', models.DateField(db_column='FechaSalida')),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('adultos', models.PositiveIntegerField()),
                ('niños', models.PositiveIntegerField()),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('idhabitacion', models.ForeignKey(blank=True, db_column='IdHabitacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hotel.habitaciones')),
                ('idhuesped', models.ForeignKey(blank=True, db_column='idHuesped', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hotel.huespedes')),
                ('idusuario', models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservaciones',
                'managed': True,
            },
        ),
    ]
