# Generated by Django 4.2.6 on 2023-11-27 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservaciones',
            old_name='adultos',
            new_name='cantidadpersona',
        ),
        migrations.RemoveField(
            model_name='reservaciones',
            name='niños',
        ),
    ]
