# Generated by Django 4.2.6 on 2023-11-26 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('idempleados', models.AutoField(db_column='IdEmpleados', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'empleados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Huespedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'huespedes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('idservicio', models.AutoField(db_column='IdServicio', primary_key=True, serialize=False)),
                ('nombreservicio', models.CharField(db_column='NombreServicio', max_length=40)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=60)),
                ('precio', models.FloatField(db_column='Precio')),
                ('iva', models.FloatField(db_column='IVA')),
                ('fecha', models.DateField(db_column='Fecha')),
            ],
            options={
                'db_table': 'servicios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipohabitaciones',
            fields=[
                ('idtipohabitacion', models.AutoField(db_column='IdTipoHabitacion', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('categoria', models.CharField(max_length=40)),
                ('imagen1', models.ImageField(blank=True, max_length=255, null=True, upload_to='tipohabitacion/', verbose_name='imagen1')),
                ('imagen2', models.ImageField(blank=True, max_length=255, null=True, upload_to='tipohabitacion/', verbose_name='imagen2')),
                ('imagen3', models.ImageField(blank=True, max_length=255, null=True, upload_to='tipohabitacion/', verbose_name='imagen3')),
                ('imagen4', models.ImageField(blank=True, max_length=255, null=True, upload_to='tipohabitacion/', verbose_name='imagen4')),
                ('descripcion', models.TextField(null=True, verbose_name='descripcion')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='detalle')),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'tipohabitaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('idhabitacion', models.AutoField(db_column='IdHabitacion', primary_key=True, serialize=False)),
                ('numhabitacion', models.CharField(db_column='NumHabitacion', max_length=10)),
                ('idtipohabitacion', models.ForeignKey(blank=True, db_column='IdTipoHabitacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hotel.tipohabitaciones')),
            ],
            options={
                'db_table': 'habitaciones',
                'managed': True,
            },
        ),
    ]
