# Generated by Django 4.2.6 on 2023-11-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='crear_eventos',
            fields=[
                ('idevento', models.AutoField(db_column='IdEvento', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('imagen', models.ImageField(upload_to='eventos/', verbose_name='imagen')),
                ('parrafo', models.TextField()),
                ('descripcion', models.TextField(null=True, verbose_name='descripcion')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='detalle')),
            ],
        ),
    ]
